# Generated by Django 4.2.10 on 2025-04-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('manage_inventory', 'Can manage inventory'), ('view_inventory', 'Can view inventory'), ('update_inventory', 'Can update inventory'), ('delete_inventory', 'Can delete inventory')],
            },
        ),
    ]
